export const ADD_ING = "ADD_ING";
export const REM_ING = "REM_ING";
export const SET_ING = "SET_ING";
export const SET_INGREDIENT = "SET_INGREDIENT";
export const FETCH_ING_FAILED = "FETCH_ING_FAILED";

export const PURCHASE_BURGER_START = "PURCHASE_BURGER_START";
export const PURCHASE_BURGER_SUCCESS = "PURCHASE_BURGER_SUCCESS";
export const PURCHASE_BURGER_FAIL = "PURCHASE_BURGER_FAIL";
export const PURCHASE_INIT = "PURCHASE_INIT";
export const PURCHASE_BURGER = "PURCHASE_BURGER";

export const FETCH_ORDERS_INIT = "FETCH_ORDERS_INIT";
export const FETCH_ORDERS_SUCCESS = "FETCH_ORDERS_SUCCESS";
export const FETCH_ORDERS_FAIL = "FETCH_ORDERS_FAIL";
export const FETCH_ORDERS = "FETCH_ORDERS";

export const AUTH_START = "AUTH_START";
export const AUTH_USER = "AUTH_USER";
export const AUTH_SUCCESS = "AUTH_SUCCESS";
export const AUTH_FAIL = "AUTH_FAIL";
export const AUTH_LOGOUT = "AUTH_LOGOUT";
export const AUTH_CHECK_STATE = "AUTH_CHECK_STATE";
export const AUTH_INIT_LOGOUT = "AUTH_INIT_LOGOUT";
export const AUTH_CHECK_TIMEOUT = "AUTH_CHECK_TIMEOUT";
